stages:
  data_ingestion:
    cmd: python src/AlzheimerClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/AlzheimerClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/dataset/AugmentedAlzheimerDataset

  training:
    cmd: python src/AlzheimerClassifier/pipeline/stage_02_model_trainer.py
    deps:
      - src/AlzheimerClassifier/pipeline/stage_02_model_trainer.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_ingestion/dataset/AugmentedAlzheimerDataset
    outs:
      - artifacts/training/model.Xception.keras

    
  evaluation:
    cmd: python src/AlzheimerClassifier/pipeline/stage_03_model_evaluator.py
    deps:
      - src/AlzheimerClassifier/pipeline/stage_03_model_evaluator.py
      - params.yaml
      - config/config.yaml
      - artifacts/training/model.Xception.keras
    metrics:
      - scores.json:
          cache: False

