artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1xBrgJTMB9VxYFw2Aof28INrIyVHoGknd/view?usp=sharing
  local_data_file: artifacts/data_ingestion/alzheimer.zip
  unzip_dir: artifacts/data_ingestion/dataset

training:
  root_dir: artifacts/training
  model_path: artifacts/training/Xception.model.keras
  